/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package edu.netosoft.java8.gradle;

public class App{
	public static void main(String[] args){
		System.out.println("Hello, World!");
	}
}
